remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Introduction to the RSP UK Tour]
description: [A GitHub Pages site to accompany the tour.]